spring.application.name=demo
spring.security.user.password=tejas

#___________________________________________________________________________________________________
#custom properties which can be used across the project using @Value("${}}")
#___________________________________________________________________________

myAnime.favourite = 'Hunter X Hunter'
myAnime.isekai = 'Mushok Tensei'

#___________________________________________________________________________________________________

spring.main.lazy-initialization = true



